### ISSUE TITLE
Push gem

### ISSUE THREAD

**Issue by m4ce** [sensu-plugins/sensu-plugins-selinux#1]
Hi,

would it be possible for you to push the gem to rubygems.org?

This way the plugin can be installed through the standard sensu plugin installation.

Cheers,
Matteo

**Comment by eheydrick** [comment]
Hi Matteo, I've pushed [0.0.4](https://rubygems.org/gems/sensu-plugins-selinux/versions/0.0.4) to rubygems. Thanks for noticing!
